# Data cleaning 

# load all libraries

library(readr)
library(tidyverse)
library(tableone)

# load data

SGLT2 <- read.csv("mi_sglt2.csv")
View(SGLT2)

# This file cleans and analyses the dataset "mi_sglt2" 

#### Creating SGLT2 only dataset for table 1 ####
# Creating the SGLT2_only dataset

SGLT2_only <- SGLT2%>%
  filter(alloc == "SGLT2")

#### Table 1 ####
# Table 1 for the overall dataset and study (characteristics in this study)

vars_all <- c("sex", "age", "bmi_bl", "sbp_bl")

catVars_all <- c("sex")

table1_all <- CreateTableOne(
  vars = vars_all,
  strata = "alloc",           
  data = SGLT2,
  factorVars = catVars_all
)

print(table1_all, showAllLevels = TRUE)
View(table1_all)

# Table 1 for SGLT2_only 

vars <- c("sex", "age", "bmi_bl")

catVars <- c("sex")

table1 <- CreateTableOne(
  vars = vars,
  strata = "adherence_flg",           
  data = SGLT2_only,
  factorVars = catVars
)

print(table1, showAllLevels = TRUE)
View(table1)

#### Chi Square for sex  ####

# Sex chi square

sex_chi <- matrix(c(124, 26, 689, 158), nrow = 2, byrow = TRUE,
                  dimnames = list(sex = c("Female", "Male"),
                                  adherence_flg = c(1, 0)))

chisq.test(sex_chi, correct = FALSE)$expected

sex_chi_test <- chisq.test(sex_chi)
sex_chi_test


#### T test for age and bmi_bl against adherence ####

# T test for age

t.test(age ~ adherence_flg, data = SGLT2_only)

# T test for bmi_bl

t.test(bmi_bl ~ adherence_flg, data = SGLT2_only)

#### Logistic regression for aim 1 ####

# No crude analysis as variables are being treated as "predictor" variables

adherence_char_fit <- glm(adherence_flg ~ bmi_bl + age + sex, family = "binomial", data = SGLT2_only)
summary(adherence_char_fit)

exp(coef(adherence_char_fit))
exp(confint.default(adherence_char_fit))

#### Sensitivity analysis ####

# Do our observations hold when restricting bmi to overweight> individuals

SGLT2_BMI_25 <- SGLT2_only%>%
  filter(bmi_bl >= 25.0)

fit_sensitivity <- glm(adherence_flg ~ bmi_bl + age + sex, family = "binomial", data = SGLT2_BMI_25)
summary(fit_sensitivity)

exp(coef(fit_sensitivity))
exp(confint.default(fit_sensitivity))

# comparing bmi cat against bmi continuous to check for non linearity

SGLT2_only$bmi_cat <- cut(
  SGLT2_only$bmi_bl,
  breaks = c(-Inf, 25, 30, Inf),
  labels = c("Normal weight (<25)", "Overweight (25-29.9)", "Obese (≥30)"),
  right = FALSE
)

fit_cat <- glm(adherence_flg ~ bmi_cat + age + sex, family = "binomial", data = SGLT2_only)
summary(fit_cat)

exp(coef(fit_cat))
exp(confint.default(fit_cat))
